"""Initial Migration

Revision ID: e2c19c7a2892
Revises: 
Create Date: 2023-01-26 09:53:19.166994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2c19c7a2892'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('blob', sa.String(), nullable=False),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('farmer_level', sa.Integer(), nullable=False),
    sa.Column('smasher_level', sa.Integer(), nullable=False),
    sa.Column('hoer_level', sa.Integer(), nullable=False),
    sa.Column('harvester_level', sa.Integer(), nullable=False),
    sa.Column('rancher_level', sa.Integer(), nullable=False),
    sa.Column('freeloader_level', sa.Integer(), nullable=False),
    sa.Column('reincarnation_level', sa.Integer(), nullable=False),
    sa.Column('ascensions', sa.Integer(), nullable=False),
    sa.Column('soul_shop_protein_shake', sa.Boolean(), nullable=False),
    sa.Column('infinity_corner_pet_damage_level', sa.Integer(), nullable=False),
    sa.Column('infinity_corner_star_level', sa.Integer(), nullable=False),
    sa.Column('expedition_shop_pet_damage_level', sa.Integer(), nullable=False),
    sa.Column('pets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farmer')
    # ### end Alembic commands ###
